### ISSUE TITLE
Domain has expired

### ISSUE THREAD

**Issue by eric-wieser** [iandennismiller/gh-impact#3]
The link in the repo description seems dead.

This one still exists, but doesn't seem to work: https://iandennismiller.github.io/gh-impact/

**Comment by iandennismiller** [comment]
Thank you for the report!

I've renewed the URL and I think the update will propagate today.

**Comment by iandennismiller** [comment]
Can I ask you a little bit about your interest in this project?  It's an academic interest of mine from a few years ago but I haven't given it any attention in a bit.  Would you be willing to share a little bit about where you're coming from and what brought you to this project?

**Comment by eric-wieser** [comment]
I'm afraid I've already forgotten why I came here a week ago. I think I was looking for finer-grained statistics (eg, all repos within an org), and just looking through the various website that claimed to measure things about github; not something this tool provides.

Anyway, thanks for following up - I was curious to see what your project did, even if it ended up not being related to what I was looking for.

**Comment by iandennismiller** [comment]
Thank you so much!

**Comment by PatMyron** [comment]
Domain expired again
